import { User, Service, Review, Attraction } from '@/shared/types';

export const mockUsers: User[] = [
  {
    id: '1',
    document: '123.456.789-00',
    documentType: 'CPF',
    name: 'Maria Silva Santos',
    email: 'maria.santos@email.com',
    whatsapp: '(35) 99123-4567',
    address: {
      street: 'Rua Wenceslau Braz',
      number: '120',
      neighborhood: 'Centro',
      city: 'São Lourenço',
      state: 'MG',
      zipCode: '37470-000',
    },
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '2',
    document: '12.345.678/0001-90',
    documentType: 'CNPJ',
    name: 'Pousada Serra Verde',
    email: 'contato@pousadaserraverde.com.br',
    whatsapp: '(35) 99234-5678',
    address: {
      street: 'Av. Dom Pedro II',
      number: '450',
      neighborhood: 'Centro',
      city: 'São Lourenço',
      state: 'MG',
      zipCode: '37470-000',
    },
    createdAt: '2024-01-10T08:30:00Z',
  },
  {
    id: '3',
    document: '987.654.321-00',
    documentType: 'CPF',
    name: 'João Pedro Oliveira',
    email: 'joao.oliveira@email.com',
    whatsapp: '(35) 99345-6789',
    address: {
      street: 'Rua Comendador Costa',
      number: '78',
      neighborhood: 'Centro',
      city: 'São Lourenço',
      state: 'MG',
      zipCode: '37470-000',
    },
    createdAt: '2024-02-01T14:20:00Z',
  },
  {
    id: '4',
    document: '23.456.789/0001-12',
    documentType: 'CNPJ',
    name: 'Restaurante Sabor Mineiro',
    email: 'sabor.mineiro@email.com',
    whatsapp: '(35) 99456-7890',
    address: {
      street: 'Praça Duque de Caxias',
      number: '22',
      neighborhood: 'Centro',
      city: 'São Lourenço',
      state: 'MG',
      zipCode: '37470-000',
    },
    createdAt: '2024-01-20T09:15:00Z',
  },
  {
    id: '5',
    document: '456.789.123-00',
    documentType: 'CPF',
    name: 'Ana Carolina Mendes',
    email: 'ana.mendes@email.com',
    whatsapp: '(35) 99567-8901',
    address: {
      street: 'Rua Barão do Rio Branco',
      number: '315',
      neighborhood: 'Centro',
      city: 'São Lourenço',
      state: 'MG',
      zipCode: '37470-000',
    },
    createdAt: '2024-02-10T11:00:00Z',
  },
  {
    id: '6',
    document: '34.567.890/0001-34',
    documentType: 'CNPJ',
    name: 'Hotel Palace',
    email: 'reservas@hotelpalace.com.br',
    whatsapp: '(35) 99678-9012',
    address: {
      street: 'Av. Getúlio Vargas',
      number: '500',
      neighborhood: 'Centro',
      city: 'São Lourenço',
      state: 'MG',
      zipCode: '37470-000',
    },
    createdAt: '2024-01-05T07:45:00Z',
  },
  {
    id: '7',
    document: '789.123.456-00',
    documentType: 'CPF',
    name: 'Carlos Eduardo Ferreira',
    email: 'carlos.ferreira@email.com',
    whatsapp: '(35) 99789-0123',
    address: {
      street: 'Rua Major Prates',
      number: '89',
      neighborhood: 'Centro',
      city: 'São Lourenço',
      state: 'MG',
      zipCode: '37470-000',
    },
    createdAt: '2024-02-15T16:30:00Z',
  },
  {
    id: '8',
    document: '45.678.901/0001-56',
    documentType: 'CNPJ',
    name: 'Agência Trilhas da Mantiqueira',
    email: 'contato@trilhasmantiqueira.com.br',
    whatsapp: '(35) 99890-1234',
    address: {
      street: 'Rua Coronel José Justino',
      number: '156',
      neighborhood: 'Centro',
      city: 'São Lourenço',
      state: 'MG',
      zipCode: '37470-000',
    },
    createdAt: '2024-01-25T13:10:00Z',
  },
  {
    id: '9',
    document: '321.654.987-00',
    documentType: 'CPF',
    name: 'Beatriz Almeida Costa',
    email: 'beatriz.costa@email.com',
    whatsapp: '(35) 99901-2345',
    address: {
      street: 'Rua Cel. Ribeiro de Souza',
      number: '234',
      neighborhood: 'Centro',
      city: 'São Lourenço',
      state: 'MG',
      zipCode: '37470-000',
    },
    createdAt: '2024-02-20T10:45:00Z',
  },
  {
    id: '10',
    document: '56.789.012/0001-78',
    documentType: 'CNPJ',
    name: 'Atelier Artesanato Mineiro',
    email: 'atelier@artesanatomineiro.com.br',
    whatsapp: '(35) 99012-3456',
    address: {
      street: 'Rua Prefeito Gabriel Passos',
      number: '67',
      neighborhood: 'Centro',
      city: 'São Lourenço',
      state: 'MG',
      zipCode: '37470-000',
    },
    createdAt: '2024-02-05T15:20:00Z',
  },
];

export const mockServices: Service[] = [
  {
    id: '1',
    userId: '1',
    name: 'Guia Turística Especializada',
    description:
      'Passeios guiados pela região de São Lourenço com foco em história local, arquitetura colonial e fontes minerais. Atendimento personalizado em português, inglês e espanhol.',
    category: 'guide',
    images: ['https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&h=600&fit=crop'],
    whatsapp: '(35) 99123-4567',
    email: 'maria.santos@email.com',
    address: {
      street: 'Rua Wenceslau Braz',
      number: '120',
      neighborhood: 'Centro',
      city: 'São Lourenço',
      state: 'MG',
    },
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '2',
    userId: '2',
    name: 'Pousada Serra Verde',
    description:
      'Pousada aconchegante com vista para a Serra da Mantiqueira. Café da manhã colonial incluído, quartos com varanda, piscina aquecida e jardim. Ambiente familiar e tranquilo.',
    category: 'inn',
    images: [
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&h=600&fit=crop',
    ],
    whatsapp: '(35) 99234-5678',
    email: 'contato@pousadaserraverde.com.br',
    address: {
      street: 'Av. Dom Pedro II',
      number: '450',
      neighborhood: 'Centro',
      city: 'São Lourenço',
      state: 'MG',
    },
    createdAt: '2024-01-10T08:30:00Z',
    updatedAt: '2024-02-15T14:20:00Z',
  },
  {
    id: '3',
    userId: '3',
    name: 'Passeio de Balão - Voo Panorâmico',
    description:
      'Experimente voar sobre São Lourenço ao nascer do sol. Voo de aproximadamente 1 hora com vista privilegiada da Serra da Mantiqueira. Inclui brinde e certificado de voo.',
    category: 'tour-agency',
    images: ['https://images.unsplash.com/photo-1500835556837-99ac94a94552?w=800&h=600&fit=crop'],
    whatsapp: '(35) 99345-6789',
    email: 'joao.oliveira@email.com',
    address: {
      street: 'Rua Comendador Costa',
      number: '78',
      neighborhood: 'Centro',
      city: 'São Lourenço',
      state: 'MG',
    },
    createdAt: '2024-02-01T14:20:00Z',
    updatedAt: '2024-02-01T14:20:00Z',
  },
  {
    id: '4',
    userId: '4',
    name: 'Restaurante Sabor Mineiro',
    description:
      'Culinária tradicional mineira com ingredientes frescos da região. Especialidades: tutu, feijão tropeiro, frango caipira e doces caseiros. Ambiente rústico e acolhedor.',
    category: 'restaurant',
    images: [
      'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&h=600&fit=crop',
    ],
    whatsapp: '(35) 99456-7890',
    email: 'sabor.mineiro@email.com',
    address: {
      street: 'Praça Duque de Caxias',
      number: '22',
      neighborhood: 'Centro',
      city: 'São Lourenço',
      state: 'MG',
    },
    createdAt: '2024-01-20T09:15:00Z',
    updatedAt: '2024-01-20T09:15:00Z',
  },
  {
    id: '5',
    userId: '5',
    name: 'Fotografia de Viagem',
    description:
      'Ensaios fotográficos em pontos turísticos de São Lourenço. Book individual, casal, família ou eventos. Entrega digital em até 7 dias.',
    category: 'photography',
    images: ['https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=800&h=600&fit=crop'],
    whatsapp: '(35) 99567-8901',
    email: 'ana.mendes@email.com',
    address: {
      street: 'Rua Barão do Rio Branco',
      number: '315',
      neighborhood: 'Centro',
      city: 'São Lourenço',
      state: 'MG',
    },
    createdAt: '2024-02-10T11:00:00Z',
    updatedAt: '2024-02-10T11:00:00Z',
  },
  {
    id: '6',
    userId: '6',
    name: 'Hotel Palace',
    description:
      'Hotel histórico no centro de São Lourenço. Construção de 1920 totalmente restaurada. Quartos elegantes, restaurante gourmet, spa com águas termais e serviço de excelência.',
    category: 'hotel',
    images: [
      'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&h=600&fit=crop',
    ],
    whatsapp: '(35) 99678-9012',
    email: 'reservas@hotelpalace.com.br',
    address: {
      street: 'Av. Getúlio Vargas',
      number: '500',
      neighborhood: 'Centro',
      city: 'São Lourenço',
      state: 'MG',
    },
    createdAt: '2024-01-05T07:45:00Z',
    updatedAt: '2024-02-20T16:30:00Z',
  },
  {
    id: '7',
    userId: '7',
    name: 'Transfer Executivo',
    description:
      'Transporte com conforto e segurança do aeroporto de Guarulhos, Congonhas, Viracopos ou Confins para São Lourenço. Veículos climatizados e motoristas experientes.',
    category: 'transport',
    images: ['https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=800&h=600&fit=crop'],
    whatsapp: '(35) 99789-0123',
    email: 'carlos.ferreira@email.com',
    address: {
      street: 'Rua Major Prates',
      number: '89',
      neighborhood: 'Centro',
      city: 'São Lourenço',
      state: 'MG',
    },
    createdAt: '2024-02-15T16:30:00Z',
    updatedAt: '2024-02-15T16:30:00Z',
  },
  {
    id: '8',
    userId: '8',
    name: 'Trilhas da Mantiqueira',
    description:
      'Aventuras na Serra da Mantiqueira com trilhas guiadas, rapel, cachoeiras e mirantes. Roteiros de meio período ou dia completo. Equipamentos inclusos.',
    category: 'tour-agency',
    images: [
      'https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&h=600&fit=crop',
    ],
    whatsapp: '(35) 99890-1234',
    email: 'contato@trilhasmantiqueira.com.br',
    address: {
      street: 'Rua Coronel José Justino',
      number: '156',
      neighborhood: 'Centro',
      city: 'São Lourenço',
      state: 'MG',
    },
    createdAt: '2024-01-25T13:10:00Z',
    updatedAt: '2024-01-25T13:10:00Z',
  },
  {
    id: '9',
    userId: '9',
    name: 'Organização de Eventos Corporativos',
    description:
      'Planejamento e execução de eventos empresariais em São Lourenço. Workshops, convenções, team building. Estrutura completa e suporte local.',
    category: 'events',
    images: ['https://images.unsplash.com/photo-1511578314322-379afb476865?w=800&h=600&fit=crop'],
    whatsapp: '(35) 99901-2345',
    email: 'beatriz.costa@email.com',
    address: {
      street: 'Rua Cel. Ribeiro de Souza',
      number: '234',
      neighborhood: 'Centro',
      city: 'São Lourenço',
      state: 'MG',
    },
    createdAt: '2024-02-20T10:45:00Z',
    updatedAt: '2024-02-20T10:45:00Z',
  },
  {
    id: '10',
    userId: '10',
    name: 'Atelier Artesanato Mineiro',
    description:
      'Peças exclusivas em cerâmica, madeira e tecido. Arte local com identidade mineira. Oficinas criativas para visitantes. Encomendas personalizadas.',
    category: 'crafts',
    images: [
      'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=800&h=600&fit=crop',
    ],
    whatsapp: '(35) 99012-3456',
    email: 'atelier@artesanatomineiro.com.br',
    address: {
      street: 'Rua Prefeito Gabriel Passos',
      number: '67',
      neighborhood: 'Centro',
      city: 'São Lourenço',
      state: 'MG',
    },
    createdAt: '2024-02-05T15:20:00Z',
    updatedAt: '2024-02-05T15:20:00Z',
  },
  {
    id: '11',
    userId: '2',
    name: 'Spa Águas Minerais',
    description:
      'Tratamentos terapêuticos com as famosas águas minerais de São Lourenço. Massagens, banhos termais, aromaterapia e day spa. Ambiente relaxante.',
    category: 'inn',
    images: ['https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&h=600&fit=crop'],
    whatsapp: '(35) 99234-5678',
    email: 'contato@pousadaserraverde.com.br',
    address: {
      street: 'Av. Dom Pedro II',
      number: '450',
      neighborhood: 'Centro',
      city: 'São Lourenço',
      state: 'MG',
    },
    createdAt: '2024-02-12T09:00:00Z',
    updatedAt: '2024-02-12T09:00:00Z',
  },
  {
    id: '12',
    userId: '4',
    name: 'Café Colonial da Praça',
    description:
      'Café da tarde tradicional mineiro com mais de 30 itens. Pães caseiros, queijos, geleias, bolos e quitandas. Servido na varanda com vista para a praça.',
    category: 'restaurant',
    images: ['https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&h=600&fit=crop'],
    whatsapp: '(35) 99456-7890',
    email: 'sabor.mineiro@email.com',
    address: {
      street: 'Praça Duque de Caxias',
      number: '22',
      neighborhood: 'Centro',
      city: 'São Lourenço',
      state: 'MG',
    },
    createdAt: '2024-02-18T08:00:00Z',
    updatedAt: '2024-02-18T08:00:00Z',
  },
  {
    id: '13',
    userId: '1',
    name: 'Tour Histórico e Cultural',
    description:
      'Conheça a história de São Lourenço através de seus monumentos, igrejas e construções históricas. Passeio a pé de 3 horas com paradas estratégicas.',
    category: 'guide',
    images: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&h=600&fit=crop'],
    whatsapp: '(35) 99123-4567',
    email: 'maria.santos@email.com',
    address: {
      street: 'Rua Wenceslau Braz',
      number: '120',
      neighborhood: 'Centro',
      city: 'São Lourenço',
      state: 'MG',
    },
    createdAt: '2024-02-22T11:30:00Z',
    updatedAt: '2024-02-22T11:30:00Z',
  },
  {
    id: '14',
    userId: '8',
    name: 'Passeio de Bicicleta - Circuito das Águas',
    description:
      'Pedale pelas cidades do Circuito das Águas. Rota de 40km com paradas em São Lourenço, Caxambu e Cambuquira. Bicicletas e equipamentos inclusos.',
    category: 'tour-agency',
    images: ['https://images.unsplash.com/photo-1541625602330-2277a4c46182?w=800&h=600&fit=crop'],
    whatsapp: '(35) 99890-1234',
    email: 'contato@trilhasmantiqueira.com.br',
    address: {
      street: 'Rua Coronel José Justino',
      number: '156',
      neighborhood: 'Centro',
      city: 'São Lourenço',
      state: 'MG',
    },
    createdAt: '2024-02-08T14:15:00Z',
    updatedAt: '2024-02-08T14:15:00Z',
  },
  {
    id: '15',
    userId: '6',
    name: 'Jantar Romântico',
    description:
      'Experiência gastronômica exclusiva com menu degustação harmonizado. Ambiente intimista com música ao vivo. Reservas antecipadas.',
    category: 'hotel',
    images: ['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&h=600&fit=crop'],
    whatsapp: '(35) 99678-9012',
    email: 'reservas@hotelpalace.com.br',
    address: {
      street: 'Av. Getúlio Vargas',
      number: '500',
      neighborhood: 'Centro',
      city: 'São Lourenço',
      state: 'MG',
    },
    createdAt: '2024-02-14T17:00:00Z',
    updatedAt: '2024-02-14T17:00:00Z',
  },
  {
    id: '16',
    userId: '7',
    name: 'City Tour Privativo',
    description:
      'Conheça São Lourenço com todo conforto. Roteiro personalizado visitando Parque das Águas, teleférico, fontes e principais atrativos. Até 4 pessoas.',
    category: 'transport',
    images: ['https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&h=600&fit=crop'],
    whatsapp: '(35) 99789-0123',
    email: 'carlos.ferreira@email.com',
    address: {
      street: 'Rua Major Prates',
      number: '89',
      neighborhood: 'Centro',
      city: 'São Lourenço',
      state: 'MG',
    },
    createdAt: '2024-02-16T10:00:00Z',
    updatedAt: '2024-02-16T10:00:00Z',
  },
  {
    id: '17',
    userId: '5',
    name: 'Ensaio Pré-Wedding nas Montanhas',
    description:
      'Book de noivos com cenários deslumbrantes da Serra da Mantiqueira. Locações exclusivas, tratamento profissional e álbum digital premium.',
    category: 'photography',
    images: ['https://images.unsplash.com/photo-1519741497674-611481863552?w=800&h=600&fit=crop'],
    whatsapp: '(35) 99567-8901',
    email: 'ana.mendes@email.com',
    address: {
      street: 'Rua Barão do Rio Branco',
      number: '315',
      neighborhood: 'Centro',
      city: 'São Lourenço',
      state: 'MG',
    },
    createdAt: '2024-02-19T13:45:00Z',
    updatedAt: '2024-02-19T13:45:00Z',
  },
  {
    id: '18',
    userId: '10',
    name: 'Oficina de Cerâmica',
    description:
      'Aprenda técnicas tradicionais de modelagem em argila. Aula de 2 horas com produção de peça personalizada. Material incluso. Grupos de até 6 pessoas.',
    category: 'crafts',
    images: ['https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=800&h=600&fit=crop'],
    whatsapp: '(35) 99012-3456',
    email: 'atelier@artesanatomineiro.com.br',
    address: {
      street: 'Rua Prefeito Gabriel Passos',
      number: '67',
      neighborhood: 'Centro',
      city: 'São Lourenço',
      state: 'MG',
    },
    createdAt: '2024-02-21T15:30:00Z',
    updatedAt: '2024-02-21T15:30:00Z',
  },
  {
    id: '19',
    userId: '9',
    name: 'Casamento Completo',
    description:
      'Organização total do seu casamento em São Lourenço. Cerimônia, recepção, decoração, buffet e coordenação. Locais paradisíacos disponíveis.',
    category: 'events',
    images: ['https://images.unsplash.com/photo-1519167758481-83f29da8c2b6?w=800&h=600&fit=crop'],
    whatsapp: '(35) 99901-2345',
    email: 'beatriz.costa@email.com',
    address: {
      street: 'Rua Cel. Ribeiro de Souza',
      number: '234',
      neighborhood: 'Centro',
      city: 'São Lourenço',
      state: 'MG',
    },
    createdAt: '2024-02-23T09:20:00Z',
    updatedAt: '2024-02-23T09:20:00Z',
  },
  {
    id: '20',
    userId: '3',
    name: 'Voo de Paraglider',
    description:
      'Voe de parapente sobre a Serra da Mantiqueira. Voo duplo com instrutor credenciado. Duração de 15-25 minutos. Fotos e vídeos inclusos.',
    category: 'tour-agency',
    images: ['https://images.unsplash.com/photo-1521058419923-fafb69a2e4c0?w=800&h=600&fit=crop'],
    whatsapp: '(35) 99345-6789',
    email: 'joao.oliveira@email.com',
    address: {
      street: 'Rua Comendador Costa',
      number: '78',
      neighborhood: 'Centro',
      city: 'São Lourenço',
      state: 'MG',
    },
    createdAt: '2024-02-25T12:00:00Z',
    updatedAt: '2024-02-25T12:00:00Z',
  },
];

export const mockReviews: Review[] = [
  {
    id: '1',
    serviceId: '1',
    rating: 5,
    comment:
      'Maria é uma guia excepcional! Conhece cada detalhe da história de São Lourenço. Recomendo muito!',
    authorName: 'Roberto Silva',
    createdAt: '2024-02-10T14:30:00Z',
  },
  {
    id: '2',
    serviceId: '1',
    rating: 5,
    comment: 'Passeio maravilhoso, muito bem explicado e com paradas estratégicas.',
    authorName: 'Juliana Mendes',
    createdAt: '2024-02-15T10:20:00Z',
  },
  {
    id: '3',
    serviceId: '2',
    rating: 5,
    comment:
      'Pousada incrível! Vista sensacional, café da manhã delicioso e atendimento impecável.',
    authorName: 'Marcos Oliveira',
    createdAt: '2024-02-08T09:15:00Z',
  },
  {
    id: '4',
    serviceId: '2',
    rating: 4,
    comment: 'Muito boa! Apenas o WiFi poderia ser mais rápido, mas no geral ótima experiência.',
    authorName: 'Patricia Costa',
    createdAt: '2024-02-12T16:45:00Z',
  },
  {
    id: '5',
    serviceId: '2',
    rating: 5,
    comment: 'Ambiente aconchegante e familiar. Voltaremos com certeza!',
    createdAt: '2024-02-18T11:30:00Z',
  },
  {
    id: '6',
    serviceId: '3',
    rating: 5,
    comment: 'Experiência única! Ver São Lourenço do alto foi inesquecível.',
    authorName: 'Fernando Santos',
    createdAt: '2024-02-16T08:00:00Z',
  },
  {
    id: '7',
    serviceId: '3',
    rating: 5,
    comment: 'Voo tranquilo e seguro. João é muito profissional e atencioso.',
    authorName: 'Amanda Lima',
    createdAt: '2024-02-20T07:30:00Z',
  },
  {
    id: '8',
    serviceId: '4',
    rating: 5,
    comment: 'Comida mineira de verdade! Tudo fresquinho e saboroso. Ambiente acolhedor.',
    authorName: 'Carlos Eduardo',
    createdAt: '2024-02-05T13:20:00Z',
  },
  {
    id: '9',
    serviceId: '4',
    rating: 4,
    comment: 'Muito bom! Porções generosas e preço justo. Recomendo o frango caipira.',
    authorName: 'Renata Alves',
    createdAt: '2024-02-11T12:45:00Z',
  },
  {
    id: '10',
    serviceId: '4',
    rating: 5,
    comment: 'Melhor tutu à mineira que já comi! Atendimento familiar e aconchegante.',
    createdAt: '2024-02-17T14:10:00Z',
  },
  {
    id: '11',
    serviceId: '5',
    rating: 5,
    comment: 'Ana é incrível! Fotos lindas e muita paciência. Adoramos o resultado.',
    authorName: 'Lucas e Marina',
    createdAt: '2024-02-21T15:30:00Z',
  },
  {
    id: '12',
    serviceId: '5',
    rating: 5,
    comment: 'Profissionalismo de alto nível. As fotos ficaram perfeitas!',
    authorName: 'Gabriela Rocha',
    createdAt: '2024-02-24T10:00:00Z',
  },
  {
    id: '13',
    serviceId: '6',
    rating: 5,
    comment: 'Hotel maravilhoso! Construção histórica muito bem preservada. Spa excepcional.',
    authorName: 'Ricardo Martins',
    createdAt: '2024-02-07T17:00:00Z',
  },
  {
    id: '14',
    serviceId: '6',
    rating: 5,
    comment: 'Experiência premium do início ao fim. Voltaremos para aniversário de casamento.',
    authorName: 'Daniela e Paulo',
    createdAt: '2024-02-14T09:30:00Z',
  },
  {
    id: '15',
    serviceId: '6',
    rating: 4,
    comment: 'Muito elegante e bem localizado. Apenas o estacionamento é pequeno.',
    authorName: 'André Souza',
    createdAt: '2024-02-19T11:15:00Z',
  },
  {
    id: '16',
    serviceId: '7',
    rating: 5,
    comment: 'Pontualidade e conforto. Carlos é muito educado e dirigiu com segurança.',
    authorName: 'Beatriz Fernandes',
    createdAt: '2024-02-22T08:45:00Z',
  },
  {
    id: '17',
    serviceId: '7',
    rating: 5,
    comment: 'Transfer impecável! Carro limpo e climatizado.',
    createdAt: '2024-02-25T07:20:00Z',
  },
  {
    id: '18',
    serviceId: '8',
    rating: 5,
    comment: 'Trilha incrível! Guias experientes e paisagens deslumbrantes.',
    authorName: 'Rafael Costa',
    createdAt: '2024-02-09T16:30:00Z',
  },
  {
    id: '19',
    serviceId: '8',
    rating: 5,
    comment: 'Aventura segura e emocionante. Equipamentos de qualidade.',
    authorName: 'Camila Santos',
    createdAt: '2024-02-13T14:50:00Z',
  },
  {
    id: '20',
    serviceId: '8',
    rating: 4,
    comment: 'Muito bom! Apenas o horário de início poderia ser mais flexível.',
    authorName: 'Thiago Oliveira',
    createdAt: '2024-02-18T15:20:00Z',
  },
  {
    id: '21',
    serviceId: '9',
    rating: 5,
    comment: 'Organizou nosso evento corporativo perfeitamente. Tudo saiu conforme planejado!',
    authorName: 'Empresa TechSul',
    createdAt: '2024-02-23T10:30:00Z',
  },
  {
    id: '22',
    serviceId: '10',
    rating: 5,
    comment: 'Peças lindas e autênticas! Atendimento personalizado e carinhoso.',
    authorName: 'Mariana Ribeiro',
    createdAt: '2024-02-06T11:40:00Z',
  },
  {
    id: '23',
    serviceId: '10',
    rating: 5,
    comment: 'Arte mineira de verdade. Comprei várias peças para presentear.',
    createdAt: '2024-02-15T13:15:00Z',
  },
  {
    id: '24',
    serviceId: '11',
    rating: 5,
    comment: 'Spa maravilhoso! Banho termal relaxante e massagem divina.',
    authorName: 'Luciana Almeida',
    createdAt: '2024-02-17T16:20:00Z',
  },
  {
    id: '25',
    serviceId: '11',
    rating: 5,
    comment: 'Melhor day spa da região. Águas minerais realmente fazem diferença.',
    authorName: 'Fernanda Costa',
    createdAt: '2024-02-22T09:45:00Z',
  },
  {
    id: '26',
    serviceId: '12',
    rating: 5,
    comment: 'Café colonial imperdível! Mais de 30 itens deliciosos.',
    authorName: 'José Antonio',
    createdAt: '2024-02-20T15:30:00Z',
  },
  {
    id: '27',
    serviceId: '12',
    rating: 4,
    comment: 'Muito bom, mas lotado aos finais de semana. Vale a pena reservar.',
    authorName: 'Sandra Lopes',
    createdAt: '2024-02-24T14:00:00Z',
  },
  {
    id: '28',
    serviceId: '13',
    rating: 5,
    comment: 'Tour histórico fascinante! Maria conhece cada pedra da cidade.',
    authorName: 'Eduardo Pires',
    createdAt: '2024-02-25T11:20:00Z',
  },
  {
    id: '29',
    serviceId: '14',
    rating: 5,
    comment: 'Passeio de bike maravilhoso! Paisagens incríveis do Circuito das Águas.',
    authorName: 'Rodrigo Nunes',
    createdAt: '2024-02-10T17:15:00Z',
  },
  {
    id: '30',
    serviceId: '14',
    rating: 4,
    comment: 'Ótimo passeio, apenas um pouco cansativo para iniciantes.',
    authorName: 'Paula Cristina',
    createdAt: '2024-02-16T10:50:00Z',
  },
  {
    id: '31',
    serviceId: '15',
    rating: 5,
    comment: 'Jantar romântico perfeito! Menu degustação excepcional e música ao vivo.',
    authorName: 'Bruno e Carla',
    createdAt: '2024-02-19T20:30:00Z',
  },
  {
    id: '32',
    serviceId: '16',
    rating: 5,
    comment: 'City tour privativo excelente! Carlos adaptou o roteiro aos nossos interesses.',
    authorName: 'Família Moreira',
    createdAt: '2024-02-21T12:40:00Z',
  },
  {
    id: '33',
    serviceId: '17',
    rating: 5,
    comment: 'Ensaio lindo! Ana captou momentos mágicos nas montanhas.',
    authorName: 'Lucas e Thais',
    createdAt: '2024-02-23T16:00:00Z',
  },
  {
    id: '34',
    serviceId: '18',
    rating: 5,
    comment: 'Oficina incrível! Aprendi muito e me diverti. Recomendo!',
    authorName: 'Isabella Martins',
    createdAt: '2024-02-24T14:30:00Z',
  },
  {
    id: '35',
    serviceId: '18',
    rating: 5,
    comment: 'Experiência maravilhosa! Professora muito paciente e talentosa.',
    createdAt: '2024-02-26T15:45:00Z',
  },
  {
    id: '36',
    serviceId: '19',
    rating: 5,
    comment: 'Beatriz organizou nosso casamento dos sonhos! Tudo perfeito!',
    authorName: 'Marcos e Juliana',
    createdAt: '2024-02-25T18:00:00Z',
  },
  {
    id: '37',
    serviceId: '20',
    rating: 5,
    comment: 'Voo de paraglider sensacional! Adrenalina e paisagem deslumbrante.',
    authorName: 'Vinicius Cardoso',
    createdAt: '2024-02-26T14:20:00Z',
  },
  {
    id: '38',
    serviceId: '1',
    rating: 4,
    comment: 'Guia muito boa, apenas o passeio poderia ser um pouco mais longo.',
    authorName: 'Helena Barros',
    createdAt: '2024-02-27T10:15:00Z',
  },
  {
    id: '39',
    serviceId: '3',
    rating: 5,
    comment: 'Realizei um sonho! Voo tranquilo e emocionante ao mesmo tempo.',
    createdAt: '2024-02-27T08:30:00Z',
  },
  {
    id: '40',
    serviceId: '6',
    rating: 5,
    comment: 'Hotel histórico com toda infraestrutura moderna. Combinação perfeita!',
    authorName: 'Alberto Gonçalves',
    createdAt: '2024-02-26T16:45:00Z',
  },
  {
    id: '41',
    serviceId: '8',
    rating: 5,
    comment: 'Melhor agência de aventura da região! Profissionalismo total.',
    authorName: 'Diego Almeida',
    createdAt: '2024-02-24T13:20:00Z',
  },
  {
    id: '42',
    serviceId: '4',
    rating: 5,
    comment: 'Restaurante autêntico! Senti em casa com tanta hospitalidade mineira.',
    createdAt: '2024-02-23T12:50:00Z',
  },
  {
    id: '43',
    serviceId: '2',
    rating: 5,
    comment: 'Pousada perfeita para relaxar! Jardim lindo e piscina aquecida.',
    authorName: 'Claudia Menezes',
    createdAt: '2024-02-21T17:30:00Z',
  },
  {
    id: '44',
    serviceId: '7',
    rating: 5,
    comment: 'Transfer pontual e confortável. Excelente custo-benefício.',
    authorName: 'Roberta Silva',
    createdAt: '2024-02-20T09:10:00Z',
  },
  {
    id: '45',
    serviceId: '10',
    rating: 4,
    comment: 'Loja charmosa com peças únicas. Preços um pouco altos, mas vale a qualidade.',
    authorName: 'Cristiane Rocha',
    createdAt: '2024-02-19T14:25:00Z',
  },
  {
    id: '46',
    serviceId: '11',
    rating: 5,
    comment: 'Day spa relaxante! Saí renovada das águas termais.',
    createdAt: '2024-02-26T11:00:00Z',
  },
  {
    id: '47',
    serviceId: '13',
    rating: 5,
    comment: 'Aprendi muito sobre a história local. Tour imperdível!',
    authorName: 'Miguel Santos',
    createdAt: '2024-02-27T09:40:00Z',
  },
  {
    id: '48',
    serviceId: '15',
    rating: 5,
    comment: 'Noite inesquecível! Harmonização perfeita e atendimento impecável.',
    authorName: 'Adriana e Felipe',
    createdAt: '2024-02-25T21:15:00Z',
  },
  {
    id: '49',
    serviceId: '16',
    rating: 5,
    comment: 'Conhecemos todos os pontos turísticos com conforto e segurança.',
    authorName: 'Família Andrade',
    createdAt: '2024-02-24T16:50:00Z',
  },
  {
    id: '50',
    serviceId: '20',
    rating: 5,
    comment: 'Experiência incrível! João é muito profissional e as fotos ficaram lindas.',
    authorName: 'Gustavo Lemos',
    createdAt: '2024-02-27T13:30:00Z',
  },
];

export const mockAttractions: Attraction[] = [
  {
    id: '1',
    name: 'Parque das Águas',
    description:
      'Principal cartão postal de São Lourenço, o Parque das Águas é um refúgio verde no coração da cidade. Com suas famosas fontes de águas minerais medicinais, jardins exuberantes, lagos ornamentais e arquitetura histórica, o parque oferece um ambiente perfeito para caminhadas relaxantes, piqueniques e apreciação da natureza. As águas minerais com diferentes propriedades terapêuticas podem ser degustadas gratuitamente nas fontes espalhadas pelo parque.',
    category: 'wellness',
    images: [
      'https://images.unsplash.com/photo-1564760290292-23341e4df6ec?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1519331379826-f10be5486c6f?w=800&h=600&fit=crop',
    ],
    address: 'Av. Dom Pedro II, s/n - Centro, São Lourenço - MG',
    schedule: 'Diariamente das 7h às 18h',
    entryFee: 'Gratuito',
    highlights: [
      '9 fontes de águas minerais diferentes',
      'Jardins paisagísticos',
      'Área de 430 mil m²',
      'Arquitetura histórica preservada',
    ],
  },
  {
    id: '2',
    name: 'Teleférico de São Lourenço',
    description:
      'Uma das atrações mais emocionantes da cidade, o teleférico leva os visitantes até o alto da Serra da Mantiqueira, proporcionando vistas panorâmicas espetaculares de São Lourenço e região. Durante o trajeto de aproximadamente 550 metros, é possível apreciar a mata atlântica preservada e avistar diversos pontos turísticos da cidade. No topo, há um mirante com estrutura completa, lanchonete e área para fotos.',
    category: 'adventure',
    images: [
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    ],
    address: 'Rua Coronel José Justino, 681 - Centro, São Lourenço - MG',
    schedule: 'Terça a domingo das 9h às 17h',
    entryFee: 'R$ 35,00 (adulto) | R$ 17,50 (criança)',
    highlights: [
      'Vista panorâmica da cidade',
      '550 metros de extensão',
      'Mirante no topo',
      'Altitude de 1.040 metros',
    ],
  },
  {
    id: '3',
    name: 'Estação Ferroviária e Trem das Águas',
    description:
      'A histórica Estação Ferroviária de São Lourenço é um marco arquitetônico da cidade e ponto de partida do famoso Trem das Águas. O passeio ferroviário percorre 22 km entre São Lourenço e Soledade de Minas, passando por paisagens deslumbrantes da Serra da Mantiqueira. A locomotiva histórica atravessa túneis, pontes e oferece vistas privilegiadas das montanhas. É uma viagem no tempo que combina história, natureza e cultura.',
    category: 'culture',
    images: [
      'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1464037866556-6812c9d1c72e?w=800&h=600&fit=crop',
    ],
    address: 'Praça Barão de Caxambu, s/n - Centro, São Lourenço - MG',
    schedule: 'Sábados, domingos e feriados - Consultar horários',
    entryFee: 'R$ 80,00 (adulto) | R$ 40,00 (criança)',
    highlights: [
      'Locomotiva histórica restaurada',
      'Percurso de 22 km',
      'Paisagens da Serra da Mantiqueira',
      'Passeio de aproximadamente 1h40',
    ],
  },
  {
    id: '4',
    name: 'Pico do Cristo Redentor',
    description:
      'O mirante do Cristo Redentor oferece uma das vistas mais impressionantes de São Lourenço. Localizado a 1.040 metros de altitude, o monumento do Cristo de braços abertos se tornou um símbolo da cidade. É possível chegar ao topo de carro, de teleférico ou através de trilha. O pôr do sol visto deste ponto é considerado um dos mais belos da região, com as montanhas da Serra da Mantiqueira criando um cenário inesquecível.',
    category: 'nature',
    images: [
      'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    ],
    address: 'Acesso pelo Teleférico ou Estrada do Cristo',
    schedule: 'Diariamente das 8h às 18h',
    entryFee: 'Gratuito (acesso via trilha ou estrada)',
    highlights: [
      'Vista 360° da região',
      'Monumento do Cristo Redentor',
      'Pôr do sol espetacular',
      'Trilha ecológica disponível',
    ],
  },
  {
    id: '5',
    name: 'Orquidário Municipal',
    description:
      'Um verdadeiro jardim botânico dedicado às orquídeas, o Orquidário Municipal abriga centenas de espécies nativas da Mata Atlântica e variedades exóticas. O espaço oferece um ambiente tranquilo para apreciar a beleza e diversidade dessas flores, com placas informativas sobre cada espécie. É um passeio educativo ideal para amantes da natureza e da botânica.',
    category: 'nature',
    images: [
      'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1455659817273-f96807779a8a?w=800&h=600&fit=crop',
    ],
    address: 'Parque das Águas - Av. Dom Pedro II, s/n',
    schedule: 'Diariamente das 8h às 17h',
    entryFee: 'Gratuito',
    highlights: [
      'Centenas de espécies de orquídeas',
      'Espécies nativas e exóticas',
      'Ambiente climatizado',
      'Visitas guiadas disponíveis',
    ],
  },
  {
    id: '6',
    name: 'Balneário e Termas',
    description:
      'O Balneário de São Lourenço oferece tratamentos terapêuticos com as águas minerais medicinais que tornaram a cidade famosa. Com piscinas termais, duchas, saunas e salas de massagem, o espaço proporciona relaxamento e bem-estar. Os tratamentos são recomendados para diversas condições de saúde, sempre com acompanhamento de profissionais especializados.',
    category: 'wellness',
    images: [
      'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&h=600&fit=crop',
    ],
    address: 'Parque das Águas - Av. Dom Pedro II, s/n',
    schedule: 'Segunda a sábado das 8h às 17h',
    entryFee: 'A partir de R$ 50,00 (consultar tratamentos)',
    highlights: [
      'Piscinas de águas termais',
      'Tratamentos terapêuticos',
      'Massagens e hidroterapia',
      'Profissionais especializados',
    ],
  },
  {
    id: '7',
    name: 'Centro Cultural Thomé Carvalho',
    description:
      'Instalado em um belo casarão histórico, o Centro Cultural preserva e promove a cultura local através de exposições de arte, apresentações musicais, oficinas e eventos. O espaço também abriga um acervo histórico sobre São Lourenço e região, com fotografias, documentos e objetos que contam a história da cidade desde sua fundação.',
    category: 'culture',
    images: [
      'https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop',
    ],
    address: 'Praça João Lage, 54 - Centro, São Lourenço - MG',
    schedule: 'Terça a domingo das 9h às 17h',
    entryFee: 'Gratuito',
    highlights: [
      'Exposições permanentes e temporárias',
      'Acervo histórico regional',
      'Oficinas culturais',
      'Eventos e apresentações',
    ],
  },
  {
    id: '8',
    name: 'Cachoeira da Fumaça',
    description:
      "Localizada a aproximadamente 15 km do centro da cidade, a Cachoeira da Fumaça é um dos destinos favoritos para os amantes de natureza e aventura. Com uma queda d'água de aproximadamente 30 metros, a cachoeira forma piscinas naturais perfeitas para banho. O acesso é feito por trilha moderada de cerca de 2 km através da Mata Atlântica preservada, com paisagens deslumbrantes ao longo do caminho.",
    category: 'nature',
    images: [
      'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=800&h=600&fit=crop',
    ],
    address: 'Zona Rural - Acesso pela MG-460',
    schedule: 'Diariamente (melhor visitação de manhã)',
    entryFee: 'Gratuito',
    highlights: [
      "Queda d'água de 30 metros",
      'Piscinas naturais',
      'Trilha ecológica de 2 km',
      'Mata Atlântica preservada',
    ],
  },
];
